src/Web/Pages/Expenses/Details.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASE3040.Web.Pages.Expenses
{
    public class DetailsModel : PageModel
    {
        private readonly ISender _mediator;

        public DetailsModel(ISender mediator)
        {
            _mediator = mediator;
        }
    /*
        public ToDoListDto? ToDoList { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            ToDoList = await _mediator.Send(new GetToDoList { Id = id });

            if (ToDoList == null)
            {
                return NotFound();
            }
        
            return Page();
        }*/
    } 
}

src/Web/Pages/Itinerary/Details.cshtml.cs
using ASE3040.Application.Features.Activities.Commands.Create;
using ASE3040.Application.Features.Activities.Commands.Delete;
using ASE3040.Application.Features.Activities.Commands.Edit;
using ASE3040.Application.Features.Itineraries.Commands.Delete;
using ASE3040.Application.Features.Itineraries.Commands.Edit;
using ASE3040.Application.Features.Itineraries.Queries;
using ASE3040.Web.Extensions;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASE3040.Web.Pages.Itinerary;

[Authorize]
public class Details : PageModel
{
    private readonly ISender _mediator;

    public Details(ISender mediator)
    {
        _mediator = mediator;
    }

    [BindProperty] public ItineraryDto Itinerary { get; set; } = default!;
    [BindProperty] public EditItineraryCommand EditItinerary { get; set; } = default!;
    [BindProperty] public CreateActivityCommand CreateActivity { get; set; } = default!;
    [BindProperty] public EditActivityCommand EditActivity { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int id)
    {
        var results = await _mediator.Send(new GetItineraries());
        var itinerary = results.FirstOrDefault(x => x.Id == id);
        if (itinerary == null)
        {
            return NotFound();
        }

        Itinerary = itinerary;
        return Page();
    }

    public async Task<IActionResult> OnPostEdit()
    {
        var result = await _mediator.Send(EditItinerary);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            return await OnGetAsync(EditItinerary.Id);
        }

        return RedirectToPage("Details", new { EditItinerary.Id });
    }
    
    public async Task<IActionResult> OnPostDeleteAsync([FromQuery]DeleteItineraryCommand request)
    {
        await _mediator.Send(request);
        return RedirectToPage("Index");
    }

    public async Task<IActionResult> OnPostCreateActivity()
    {
        var result = await _mediator.Send(CreateActivity);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            return await OnGetAsync(CreateActivity.ItineraryId);
        }

        return RedirectToPage("Details", new { Id = CreateActivity.ItineraryId });
    }

    public async Task<IActionResult> OnPostToggleActivity([FromQuery] ToggleActivityCommand request,
        [FromQuery] int itineraryId)
    {
        var result = await _mediator.Send(request);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            return await OnGetAsync(itineraryId);
        }

        return RedirectToPage("Details", new { Id = itineraryId });
    }

    public async Task<IActionResult> OnPostEditActivity()
    {
        var result = await _mediator.Send(EditActivity);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            return await OnGetAsync(Itinerary.Id);
        }

        return RedirectToPage("Details", new { Itinerary.Id });
    }

    public async Task<IActionResult> OnPostDeleteActivity([FromQuery] DeleteActivityCommand request,
        [FromQuery] int itineraryId)
    {
        var result = await _mediator.Send(request);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            return await OnGetAsync(itineraryId);
        }

        return RedirectToPage("Details", new { Id = itineraryId });
    }
}

src/Web/Pages/Itinerary/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using ASE3040.Application.Common.Models;
using ASE3040.Application.Features.Itineraries.Commands.Create;
using ASE3040.Application.Features.Itineraries.Queries;
using ASE3040.Web.Extensions;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASE3040.Web.Pages.Itinerary;

[Authorize]
public class IndexModel : PageModel
{
    private readonly ISender _mediator;

    public IndexModel(ISender mediator)
    {
        _mediator = mediator;
    }

    public IEnumerable<ItineraryDto> Itineraries { get; set; } = default!;

    [BindProperty]
    public CreateModel CreateInput { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync()
    {
        Itineraries = await _mediator.Send(new GetItineraries());
        return Page();
    }

    public async Task<IActionResult> OnPostCreateAsync()
    {
        if (!ModelState.IsValid)
        {
            Itineraries = await _mediator.Send(new GetItineraries());
            return Page();
        }

        var request = new CreateItineraryCommand()
        {
            Title = CreateInput.Title,
            Description = CreateInput.Description,
            Budget = CreateInput.Budget
        };

        Result result = await _mediator.Send(request);

        if (!result.Succeeded)
        {
            ModelState.AddResult(result);
            Itineraries = await _mediator.Send(new GetItineraries());
            return Page();
        }

        return RedirectToPage();
    }

    public class CreateModel
    {
        [Required]
        public string? Title { get; set; }

        public string? Description { get; set; }

        [DataType(DataType.Currency)]
        public decimal? Budget { get; set; }
    }
}

src/Web/Pages/Shared/Components/ValidationAlert/ValidationAlertViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ASE3040.Web.Pages.Shared.Components.ValidationAlert;

public class ValidationAlertViewComponent : ViewComponent
{
    public Task<IViewComponentResult> InvokeAsync()
    {
        return Task.FromResult<IViewComponentResult>(View());
    }
}

src/Web/Pages/Todo/Details.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASE3040.Web.Pages.Todo
{
    public class DetailsModel : PageModel
    {
        private readonly ISender _mediator;

        public DetailsModel(ISender mediator)
        {
            _mediator = mediator;
        }
    /*
        public ToDoListDto? ToDoList { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            ToDoList = await _mediator.Send(new GetToDoList { Id = id });

            if (ToDoList == null)
            {
                return NotFound();
            }
        
            return Page();
        }*/
    } 
}

src/Web/Pages/Itinerary/Index.cshtml
@page
@using ASE3040.Application.Features.Itineraries.Queries
@model IndexModel
@{
    ViewData["Title"] = "Your Itineraries";
    const string dateFormat = "dd MMM yyyy hh:mm tt";
    const string dateOnlyFormat = "dd MMM yyyy";
}
@if (!Model.ModelState.IsValid)
{
    @await Component.InvokeAsync("ValidationAlert")
}
<div class="container my-3">
    <div class="d-flex justify-content-between align-items-end flex-wrap">
        <h2 class="mb-0 text-gray-800">@ViewData["Title"]</h2>
        <div>
            <a class="btn py-0" data-bs-toggle="modal" data-bs-target="#createModal">
                Add Itinerary
            </a>
        </div>
    </div>
    <hr/>
    <div class="row row-cols-1 row-cols-sm-2 g-3">
        @foreach (ItineraryDto item in Model.Itineraries)
        {
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <a class="h5" style="border-bottom: 2px dotted; text-decoration: none;" asp-page="Details" asp-route-id="@(item.Id.ToString())">
                            @Html.DisplayFor(x => item.Title)
                        </a>
                        @if (item is { From: not null,To: not null })
                        {
                            <div class="text-muted mt-2">
                                <i class="far fa-calendar-alt fa-fw"></i>
                                <span class="ms-1">@item.From.Value.ToString(dateOnlyFormat)</span>
                                <span class="ms-1"> - </span>
                                <span class="ms-1">@item.To.Value.ToString(dateOnlyFormat)</span>
                            </div>
                        }
                        @if (!string.IsNullOrEmpty(item.Description))
                        {
                            <div class="mt-2">
                                <i class="far fa-sticky-note fa-fw"></i>
                                @Html.DisplayFor(x => item.Description)
                            </div>
                        }
                        @if (item.Budget.HasValue)
                        {
                            decimal expenses = item.Expenses ?? 0;
                            decimal budget = item.Budget ?? 0;
                            <div class="mt-2">
                                <i class="fas fa-money-check-alt fa-fw"></i>
                                @expenses.ToString("C") / @budget.ToString("C")
                            </div>
                        }
                        @if (item.LastModified.HasValue)
                        {
                            <div class="mt-2">
                                <small class="text-body-secondary">Last Modified @item.LastModified.Value.ToString(dateFormat)</small>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="modal fade" id="createModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="modal-content needs-validation" method="post" asp-page-handler="Create">
            <div class="modal-header">
                <h3 class="modal-title fs-5" id="staticBackdropLabel">Create new itinerary</h3>
                <button type="button" class="btn btn-outline-secondary border-0" data-bs-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label asp-for="CreateInput.Title">Title</label>
                    <input class="form-control" asp-for="CreateInput.Title">
                    <span asp-validation-for="CreateInput.Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CreateInput.Budget">Budget ($)</label>
                    <input class="form-control" asp-for="CreateInput.Budget">
                    <span asp-validation-for="CreateInput.Budget" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="CreateInput.Description">Description</label>
                    <textarea class="form-control" asp-for="CreateInput.Description"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
    $(document).ready(function() {
      $('#IndexTable').DataTable({
        columnDefs: [
            { orderable: false, targets: 7 }
        ]
      });
    });
    </script>
}